import { Inter } from "next/font/google";
import "./globals.css";

import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import NavBar from "@/components/NavBar";
import Divider from '@mui/material/Divider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ minHeight: "100vh", margin: 0 }}
      >
        <CssBaseline />
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          <NavBar />
          <Divider />
          <Box
            sx={{
              flex: 1,
              display: "flex",
              flexDirection: "column",
              p: 4,
            }}
            component="main"
          >
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
